import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { createApp } from "../src/server.mjs";
import { openCredentials } from "../src/auth.mjs";
import { AdminSessions } from "../src/admin-sessions.mjs";
import { RESET_CONFIRMATION } from "../src/admin-recovery.mjs";
const fixtureCredential = "synthetic-admin-password";

test("real application permits direct local recovery and rejects proxy reset while retaining private data", async (t) => {
  const root = await mkdtemp(join(tmpdir(), "collector-reset-server-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(join(root, "secrets"));
  await writeFile(join(root, "secrets", "admin-login.txt"), fixtureCredential);
  await mkdir(join(root, "data"));
  await writeFile(join(root, "data", "novel.txt"), "SYNTHETIC_EXISTING_NOVEL");
  const credentials = await openCredentials({ directory: join(root, "secrets") });
  const store = { path: (...parts) => join(root, "data", ...parts) };
  const sessions = await new AdminSessions({ store, binding: credentials.sessionVersion() }).load();
  const app = createApp({ store, scheduler: {}, credentials, sessionStore: sessions, trustProxy: true });
  await new Promise(resolve => app.listen(0, "127.0.0.1", resolve));
  t.after(() => new Promise(resolve => app.close(resolve)));
  const base = `http://127.0.0.1:${app.address().port}`;
  const login = await fetch(base + "/api/login", { method: "POST", headers: { "Content-Type": "application/json", Origin: base }, body: JSON.stringify({ password: fixtureCredential }) });
  const oldCookie = login.headers.get("set-cookie").split(";")[0];
  assert.equal(login.status, 200);
  const forwarded = { "X-Forwarded-For": "127.0.0.1", "X-Real-IP": "127.0.0.1" };
  assert.deepEqual(await (await fetch(base + "/api/admin-recovery", { headers: forwarded })).json(), { localAvailable: false, initialPasswordFile: "secrets/admin-login.txt" });
  const denied = await fetch(base + "/api/admin-recovery", { method: "POST", headers: { ...forwarded, "Content-Type": "application/json", Origin: base }, body: JSON.stringify({ confirmation: RESET_CONFIRMATION, nonce: "a".repeat(64) }) });
  assert.equal(denied.status, 403);
  assert.equal(credentials.verify(fixtureCredential), true);
  const challengeResponse = await fetch(base + "/api/admin-recovery");
  const challenge = await challengeResponse.json();
  const recoveryCookie = challengeResponse.headers.get("set-cookie").split(";")[0];
  const reset = await fetch(base + "/api/admin-recovery", { method: "POST", headers: { "Content-Type": "application/json", Origin: base, Cookie: recoveryCookie }, body: JSON.stringify({ confirmation: RESET_CONFIRMATION, nonce: challenge.nonce }) });
  assert.equal(reset.status, 200);
  const result = await reset.json();
  assert.equal(result.authenticated, false);
  assert.equal(credentials.verify(result.newPassword), true);
  assert.deepEqual(await (await fetch(base + "/api/session", { headers: { Cookie: oldCookie } })).json(), { authenticated: false });
  assert.equal(await readFile(join(root, "data", "novel.txt"), "utf8"), "SYNTHETIC_EXISTING_NOVEL");
  const reloaded = await new AdminSessions({ store, binding: credentials.sessionVersion() }).load();
  assert.equal(reloaded.get(oldCookie.slice("collector_session=".length)), null);
  assert.equal((await fetch(base + "/login-recovery.js")).status, 200);
});
